# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the used genome
  genome: "path/to/genome.fa"
  # the STAR index
  index: "path/to/star/index"
  # gtf file with transcripts
  annotation: "path/to/annotation.gtf"
  # tsv file with metainfo to the genes (gentype, different IDs, gene symbol)
  metainfo: "path/to/metainfo.tsv"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # model to use for deseq2 init
  model:
    - condition
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
